# Generated by Django 2.2.3 on 2019-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
