# Generated by Django 2.2.3 on 2019-08-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20190814_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='tamilName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
