# Generated by Django 2.2.3 on 2019-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20190814_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='englishName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='sinhalaName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
