# Generated by Django 2.2.3 on 2019-08-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20190813_0638'),
        ('city', '0005_auto_20190814_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('district', 'sinhalaName')},
        ),
    ]
