# Generated by Django 2.2.3 on 2019-08-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_auto_20190814_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
