# Generated by Django 2.2.3 on 2019-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('sinhalaName', models.CharField(max_length=255)),
                ('tamilName', models.CharField(max_length=255)),
                ('englishName', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('featureImage', models.CharField(max_length=255)),
                ('mapUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
