# Generated by Django 2.2.3 on 2019-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0006_auto_20190717_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/provinces/'),
        ),
        migrations.AlterField(
            model_name='province',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='mapUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='tamilName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
