# Generated by Django 2.2.3 on 2019-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0008_auto_20190721_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
