# Generated by Django 2.2.5 on 2019-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0010_auto_20190729_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='sinhalaName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='tamilName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
