# Generated by Django 2.2.3 on 2019-07-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Province', '0009_auto_20190729_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('sinhalaName', models.CharField(max_length=255, unique=True)),
                ('englishName', models.CharField(max_length=255, unique=True)),
                ('tamilName', models.CharField(max_length=255, unique=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('featureImage', models.ImageField(blank=True, null=True, upload_to='images/provinces/')),
                ('mapUrl', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Province.Province')),
            ],
        ),
    ]
