# Generated by Django 2.2.3 on 2019-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/district/'),
        ),
    ]
