# Generated by Django 2.2.5 on 2019-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20190813_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='sinhalaName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='district',
            name='tamilName',
            field=models.CharField(max_length=255),
        ),
    ]
